In [70]:
import pandas as pd
train_data = pd.read_excel('./dataset.xlsx')
train_data

                                               content  privacy
0    If this colleague of mine talks in japanese on...        1
1    “Several hours after the game, none of the tea...        1
2    @silas_hansen Yesterday my colleague said some...        1
3    RT @aarondotcompton : What can I do to make my...        1
4    @Ricardo70078700 I have a big problem buying f...        0
..                                                 ...      ...
504  #AEWDynamite  Seeing ARN, get down in that sta...        1
505  RT @FatcharasOTD : holy shit supposedly torrid...        1
506  @alaskadreaming @IngridLeary Yes well you prob...        1
507    someone needs to get fired idc do better !!!!!!        1
508          @chiIIum the principal needs to get fired        1

[509 rows x 2 columns]

In [71]:
import re

p = re.compile(r'[^\w\s]+')

train_data=train_data.replace('[^\w\s]','',regex=True)
train_data.content=train_data.content.map(lambda x:x.lower())
train_data.to_excel('train_data.xlsx')

stopwords = []
with open('./stopwords.txt', 'r', encoding='utf-8') as f:
    for line in f:
        if len(line)>0:
            stopwords.append(line.strip())
            
train_data['without_stopwords'] = train_data['content'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stopwords)]))

train_data.to_excel('processed_data.xlsx')